Updated docs build on CI

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -14,6 +14,7 @@ PYTHON_EXEC       ?= "python3.8"
 RUN_EXAMPLE_WC    ?= 
 
 .SILENT:
+.ONESHELL:
 
 # Put it first so that "make" without argument is like "make help".
 help:
@@ -40,10 +41,18 @@ generate_schematics:
 	cp $${filename%.*}.svg source/auto_sample_verilog/'
 
 run_examples: generate_schematics
-	find ../examples -type f -name "*.py" | \
-	parallel -j 4 'cd $$(dirname {}) ; \
-	${PYTHON_EXEC} $$(basename {}) &> /dev/null; \
-	if [ $$? -eq 0 ]; then echo "--- " {}; else echo "ERROR" {}; fi;'
+	export PYTHONPATH=$${PYTHONPATH}:$$(pwd)/..
+	log_dir=$$(pwd)/_run_examples_logs
+	mkdir -p $$log_dir
+	rm -rf $${log_dir}/failed.log 
+	find ../examples/${RUN_EXAMPLE_WC} -type f -name "*.py" | \
+	parallel -j 4 'log_dir=$$(pwd); \
+	cd $$(dirname {}); filename=$$(basename {}); \
+	${PYTHON_EXEC} $$(basename {}) 1> "$${log_dir}/_run_examples_logs/$${filename%.*}.log"; \
+	if [ $$? -eq 0 ]; then echo "--- " {}; \
+		else echo {} > "$${log_dir}/_run_examples_logs/failed.log"; \
+	echo "ERROR" {}; fi;'
+	if [[ -f $${log_dir}/failed.log ]]; then return 1; fi
 
 # run_examples:
 # 	find ../examples -type f -name "*.py" \
@@ -55,6 +64,7 @@ clean:
 	rm -rf build source/auto_*
 	find . -type d -name "generated" -exec rm -rf "{}" \; || true
 	find ../examples -type f -name "_*.*" -exec rm -rf "{}" \; || true
+	find ../examples -type f -name "*.log" -exec rm -rf "{}" \; || true
 
 
 .PHONY: help Makefile
